export const CREATE_CATEGORIES = 'CREATE_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADING_FALSE = 'CATEGORIES_LOADING_FALSE';
export const CATEGORIES_QUERY_ERROR = 'CATEGORIES_QUERY_ERROR';

export const CREATE_MEAL_CATEGORY = 'CREATE_MEAL_CATEGORY';
export const MEAL_CATEGORY_LOADING = 'MEAL_CATEGORY_LOADING';
export const MEAL_CATEGORY_QUERY_ERROR = 'MEAL_CATEGORY_QUERY_ERROR';
export const MEAL_CATEGORY_LOADING_FALSE = 'MEAL_CATEGORY_LOADING_FALSE';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const RECIPE_LOADING_TRUE = 'RECIPE_LOADING_TRUE';
export const RECIPE_LOADING_FALSE = 'RECIPE_LOADING_FALSE';
export const RECIPE_QUERY_ERROR = 'RECIPE_QUERY_ERROR';
export const CARD_SHOW_RECIPE = 'CARD_SHOW_RECIPE';
export const CARD_SHOW_INGREDIENTS = 'CARD_SHOW_INGREDIENTS';
export const CARD_SHOW_TOOLS = 'CARD_SHOW_TOOLS';
export const TOGGLE_RECIPE_STEP = 'TOGGLE_RECIPE_STEP';
export const TOGGLE_RECIPE_INGREDIENT = 'TOGGLE_RECIPE_INGREDIENT';

export const CREATE_INGREDIENTS = 'CREATE_INGREDIENTS';
export const INGREDIENTS_LOADING_TRUE = 'INGREDIENTS_LOADING_TRUE';
export const INGREDIENTS_LOADING_FALSE = 'INGREDIENTS_LOADING_FALSE';
export const INGREDIENTS_QUERY_ERROR = 'INGREDIENTS_QUERY_ERROR';
export const INGREDIENTS_CHANGE_FILTER = 'INGREDIENTS_CHANGE_FILTER';
